import { useState, useEffect } from 'react';
import { useNavigate, Link } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { useAuth, useComplaints, useCivicPoints, useRTIs, DEPARTMENTS, STATUS_CONFIG, type ComplaintStatus } from '@/lib/store';
import ComplaintForm from '@/components/ComplaintForm';
import ComplaintCard from '@/components/ComplaintCard';
import Navbar from '@/components/layout/Navbar';
import { Shield, Plus, LogOut, Search, Filter, FileText, MapPin, BarChart3, Bell, Award, Star } from 'lucide-react';
import { motion } from 'framer-motion';

export default function CitizenDashboard() {
  const { user, logout, isLoading: authLoading } = useAuth();
  const { complaints, addComplaint, voteComplaint, isLoading: dataLoading } = useComplaints();
  const { currentPoints, statusLevel } = useCivicPoints();
  const { fileRTI } = useRTIs();
  const navigate = useNavigate();
  const [showForm, setShowForm] = useState(false);
  const [search, setSearch] = useState('');
  const [statusFilter, setStatusFilter] = useState<ComplaintStatus | 'all'>('all');
  const [showRTI, setShowRTI] = useState<string | null>(null);

  useEffect(() => {
    if (!authLoading && !user) {
      navigate('/login');
    }
  }, [user, authLoading, navigate]);

  if (authLoading) return <div className="min-h-screen flex items-center justify-center text-muted-foreground">Loading dashboard...</div>;
  if (!user) return null;

  const myComplaints = complaints.filter(c => c.userId === user.id);
  const allComplaints = complaints;

  const filtered = (statusFilter === 'all' ? allComplaints : allComplaints.filter(c => c.status === statusFilter))
    .filter(c => !search || c.title.toLowerCase().includes(search.toLowerCase()) || c.location.toLowerCase().includes(search.toLowerCase()));

  const statusCounts = {
    all: allComplaints.length,
    pending: allComplaints.filter(c => c.status === 'pending').length,
    assigned: allComplaints.filter(c => c.status === 'assigned').length,
    in_progress: allComplaints.filter(c => c.status === 'in_progress').length,
    resolved: allComplaints.filter(c => c.status === 'resolved').length,
  };

  const handleSubmit = (data: any) => {
    addComplaint({ ...data, userId: user.id, status: 'pending' as ComplaintStatus });
    setShowForm(false);
  };

  const delayedComplaints = myComplaints.filter(c => {
    if (c.status === 'resolved') return false;
    const days = Math.floor((Date.now() - new Date(c.createdAt).getTime()) / 86400000);
    return days > 7;
  });

  const handleGenerateRTI = (c: typeof complaints[0]) => {
    fileRTI({
      complaintId: c.id,
      title: `RTI for Delayed Setup: ${c.title}`,
      department: c.department,
      content: `RIGHT TO INFORMATION ACT, 2005\nTo: The Public Information Officer\nDepartment: ${DEPARTMENTS.find(d => d.value === c.department)?.label}\nSubject: Status of Complaint ${c.id}`
    });
    setShowRTI(null);
  };

  const generateRTIContent = (c: typeof complaints[0]) => {
    return `
RIGHT TO INFORMATION ACT, 2005
To: The Public Information Officer
Department: ${DEPARTMENTS.find(d => d.value === c.department)?.label}
Subject: Status of Complaint ${c.id}

Sir/Madam,

I request the status of complaint "${c.title}" filed on ${c.createdAt}.
Please provide:
1. Handling officer name/rank.
2. Official reason for delay (7+ days).
3. Current action report.

Applicant: ${user.name}
Generated by Sarkar Connect AI.
    `.trim();
  };

  return (
    <div className="min-h-screen bg-background text-foreground overflow-hidden">
      <Navbar />
      
      {/* Decorative Background Elements */}
      <div className="fixed top-0 left-0 w-full h-full overflow-hidden pointer-events-none -z-10">
         <div className="absolute top-[-10%] right-[-5%] w-[500px] h-[500px] bg-primary/20 blur-[120px] rounded-full mix-blend-screen animate-float" />
         <div className="absolute bottom-[-10%] left-[-5%] w-[600px] h-[600px] bg-indigo-500/10 blur-[150px] rounded-full mix-blend-screen animate-float" style={{ animationDelay: '2s' }} />
         <div className="absolute top-[40%] left-[20%] w-[300px] h-[300px] bg-warning/5 blur-[100px] rounded-full mix-blend-screen animate-float" style={{ animationDelay: '4s' }} />
      </div>

      <main className="container mx-auto px-4 py-8 relative">
        <section className="mb-12 border-b border-white/[0.05] pb-10">
           <motion.div 
             initial={{ opacity: 0, y: 20 }}
             animate={{ opacity: 1, y: 0 }}
             className="flex flex-col md:flex-row items-center justify-between gap-6"
           >
              <div className="flex items-center gap-6 w-full md:w-auto">
                 <div className="relative group">
                    <div className="w-20 h-20 rounded-[1.5rem] bg-gradient-to-br from-primary/20 to-primary/5 border border-primary/20 flex items-center justify-center p-1 shadow-glow transition-all duration-500 group-hover:scale-105">
                       <div className="w-full h-full rounded-[1.2rem] bg-background flex items-center justify-center">
                          <span className="text-3xl font-black bg-gradient-to-br from-primary to-indigo-400 bg-clip-text text-transparent">
                             {user?.name?.charAt(0) || 'U'}
                          </span>
                       </div>
                    </div>
                    {statusLevel.includes('Gold') && (
                       <div className="absolute -top-3 -right-3 w-8 h-8 rounded-full bg-warning border-2 border-background flex items-center justify-center shadow-lg transform rotate-12 animate-pulse">
                          <Star className="w-4 h-4 text-black fill-black" />
                       </div>
                    )}
                 </div>
                 
                 <div>
                    <span className="text-[10px] font-black tracking-[0.3em] text-primary uppercase opacity-80 block mb-1">Citizen Portal Dashboard</span>
                    <h1 className="text-4xl font-display font-black text-white uppercase tracking-tight leading-none mb-3">Jai Hind, {user.name}</h1>
                    <div className="flex items-center gap-4">
                       <div className="flex items-center gap-2 px-3 py-1.5 rounded-full bg-white/5 border border-white/10 text-[10px] font-bold text-muted-foreground uppercase tracking-widest">
                          <MapPin className="w-3 h-3 text-primary" /> India
                       </div>
                       <Link to="/rewards" className="flex items-center gap-2 group hover:opacity-80 transition-opacity">
                          <div className="flex items-center gap-1.5 px-3 py-1.5 rounded-full bg-warning/10 border border-warning/30 text-[10px] font-black text-warning uppercase tracking-widest">
                             <Star className="w-3 h-3 fill-warning" /> {currentPoints.toLocaleString()} CP
                          </div>
                          <span className="text-[10px] font-bold text-muted-foreground group-hover:text-white transition-colors">{statusLevel}</span>
                       </Link>
                    </div>
                 </div>
              </div>
              <div className="flex gap-4">
                 <Button onClick={() => setShowForm(true)} className="h-16 px-10 bg-primary text-white font-black uppercase tracking-widest text-[11px] rounded-[1.25rem] shadow-glow flex items-center gap-2 group transition-all hover:translate-y-[-2px]">
                    <Plus className="w-5 h-5 group-hover:rotate-90 transition-transform" /> 
                    Submit New Grievance
                 </Button>
              </div>
           </motion.div>
        </section>

        {/* Dynamic Navigation/Filtering */}
        <section className="mb-12">
          <div className="flex flex-col md:flex-row items-center gap-6 mb-8">
             <div className="flex-1 w-full relative group">
                <Search className="absolute left-6 top-1/2 -translate-y-1/2 w-5 h-5 text-muted-foreground group-focus-within:text-primary transition-colors" />
                <input 
                   value={search} 
                   onChange={e => setSearch(e.target.value)} 
                   placeholder="SEARCH GLOBAL GRIEVANCE DATABASE..." 
                   className="w-full h-16 bg-white/5 border border-white/10 px-14 rounded-2xl outline-none focus:border-primary/50 focus:ring-4 focus:ring-primary/5 transition-all text-white font-bold placeholder:text-muted-foreground/30 placeholder:font-black placeholder:uppercase placeholder:tracking-widest placeholder:text-xs"
                />
             </div>
             <div className="flex gap-2 p-1.5 bg-white/5 rounded-2xl border border-white/5 h-16 w-full md:w-auto overflow-x-auto">
                {(['all', 'pending', 'assigned', 'in_progress', 'resolved'] as const).map(s => (
                  <button 
                    key={s} 
                    onClick={() => setStatusFilter(s)}
                    className={`h-full px-6 flex flex-col items-center justify-center rounded-[0.85rem] transition-all min-w-[100px] ${
                      statusFilter === s ? 'bg-white text-black font-black' : 'text-muted-foreground font-bold hover:bg-white/5'
                    }`}
                  >
                    <span className="text-[10px] uppercase tracking-widest mb-0.5">{s === 'all' ? 'Volume' : STATUS_CONFIG[s].label}</span>
                    <span className="text-sm">{statusCounts[s]}</span>
                  </button>
                ))}
             </div>
          </div>
        </section>

        {/* Accountability Notifications */}
        {delayedComplaints.length > 0 && (
          <motion.div 
            initial={{ opacity: 0, scale: 0.95 }}
            animate={{ opacity: 1, scale: 1 }}
            className="p-8 rounded-[2rem] bg-gradient-to-r from-warning/20 to-warning/5 border border-warning/30 mb-12 flex flex-col md:flex-row items-center justify-between gap-8 backdrop-blur-xl"
          >
            <div className="flex items-center gap-6">
              <div className="w-16 h-16 rounded-2xl bg-warning flex items-center justify-center shadow-[0_0_30px_rgba(234,179,8,0.4)]">
                 <FileText className="w-8 h-8 text-black" />
              </div>
              <div>
                <h3 className="text-2xl font-display font-black text-white uppercase tracking-tight">Governance Alert: Unresolved Delay</h3>
                <p className="text-muted-foreground font-medium max-w-lg leading-relaxed mt-1">
                   {delayedComplaints.length} of your grievances have passed the <span className="text-warning font-black">7-Day Protocol</span>. You are entitled to immediate RTI documentation.
                </p>
              </div>
            </div>
            <div className="flex gap-3 overflow-x-auto w-full md:w-auto pb-2 md:pb-0">
              {delayedComplaints.map(c => (
                <Button key={c.id} variant="hero" onClick={() => setShowRTI(c.id)} className="h-12 bg-black text-warning border border-warning/50 font-black text-[10px] uppercase tracking-widest px-6 hover:bg-warning hover:text-black transition-all rounded-xl">
                   File RTI: {c.id}
                </Button>
              ))}
            </div>
          </motion.div>
        )}

        {/* Complaints Grid */}
        <section className="space-y-6">
           {filtered.length === 0 ? (
             <div className="text-center py-32 glass-card">
                <Shield className="w-20 h-20 mx-auto mb-6 opacity-10 text-primary" />
                <h3 className="text-2xl font-display font-black text-white uppercase tracking-widest opacity-30">Zero Grievances Logged</h3>
                <p className="text-muted-foreground font-bold mt-4">Your oversight database is currently empty.</p>
                <Button onClick={() => setShowForm(true)} variant="ghost" className="mt-8 text-primary font-black uppercase text-xs tracking-[0.3em]">Initialize Portal +</Button>
             </div>
           ) : (
             <div className="grid grid-cols-1 gap-6">
                {filtered.map(c => (
                   <ComplaintCard key={c.id} complaint={c} onVote={(id) => voteComplaint(id, user.id)} />
                ))}
             </div>
           )}
        </section>
      </main>

      {showForm && <ComplaintForm onSubmit={handleSubmit} onClose={() => setShowForm(false)} />}

      {/* RTI Modal */}
      {showRTI && (
        <div className="fixed inset-0 z-50 bg-[#000]/90 backdrop-blur-2xl flex items-center justify-center p-4">
          <motion.div 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="glass-card w-full max-w-4xl max-h-[90vh] overflow-hidden flex flex-col border border-warning/20 shadow-[0_0_100px_rgba(234,179,8,0.1)]"
          >
            <div className="p-8 border-b border-warning/20 bg-warning/5 flex items-center justify-between">
              <div>
                <span className="text-[10px] font-black text-warning uppercase tracking-[0.3em]">Official Document Intelligence</span>
                <h3 className="text-3xl font-display font-black text-white uppercase tracking-tight mt-1">SARKAR RTI GENERATOR</h3>
              </div>
              <button 
                onClick={() => setShowRTI(null)} 
                className="w-12 h-12 flex items-center justify-center rounded-xl bg-white/5 border border-white/10 hover:bg-warning/20 hover:text-warning transition-all text-white"
              >✕</button>
            </div>
            
            <div className="flex-1 overflow-y-auto p-12 bg-[#050505]">
              <div className="max-w-2xl mx-auto border border-white/[0.05] p-12 shadow-[0_0_50px_rgba(255,255,255,0.02)]">
                <pre className="whitespace-pre-wrap text-lg text-white font-mono leading-[2] tracking-normal">
                  {generateRTIContent(complaints.find(c => c.id === showRTI)!)}
                </pre>
              </div>
            </div>

            <div className="p-8 border-t border-white/[0.05] bg-white/[0.02] flex gap-4 justify-end">
              <Button variant="ghost" onClick={() => setShowRTI(null)} className="h-14 px-10 text-white font-bold text-xs uppercase tracking-widest rounded-xl">Cancel Protocol</Button>
              <Button 
                onClick={() => {
                   handleGenerateRTI(complaints.find(c => c.id === showRTI)!);
                   alert("Smart RTI Officially Filed!");
                }}
                className="h-14 px-12 bg-warning text-black font-black text-xs uppercase tracking-[0.2em] rounded-xl shadow-lg shadow-warning/20"
              >
                File Official RTI Now
              </Button>
            </div>
          </motion.div>
        </div>
      )}
    </div>
  );
}
